name: Tag Release

on:
  push:
    tags:
      - "[0-9]+-[0-9]+-[0-9]+"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Data from FTP
        run: |
          curl ftp://ftp.rap.ucar.edu//pub/andywood/usace/sun_r.summa_mizu.tgz --output ./fixtures/sun_r.summa_mizu.tgz


      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/fixtures/sun_r.summa_mizu.tgz"
          bodyFile: ${{ github.workspace }}/RELEASE.md
          makeLatest: true
